config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    resources :tags
  end
  namespace :task do
    resources :tags
  end
  root 'projects#index'
  get 'tasks/delete'
  get 'tags/delete'
  get 'projects/last_projects'
  get 'projects/first_projects'

  resources :projects do
    resources :tasks
  end
  resources :tasks do
    end

  get 'home/alltasks' #Tasks
  get 'home/only_comp' #tasks
  get 'home/only_uncomp' #tasks
  get 'home/search' #search
  get 'home/alltags'# Tags
  get 'home/index2'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :tags, dependent: :destroy

  attribute :is_done, :boolean, default: false
  #validation
  validates :title, presence: true
  validates :uid, presence: true
  validates :project_id, presence: true

  scope :comp_tasks, -> {where(:is_done => true)}
  scope :uncomp_tasks, -> {where(:is_done => false)}

  def self.search(search)
    if search
      where(["title LIKE?", "%#{search}%"])
    else
      all
    end
  end
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task
  attr_reader :task
  before_action :set_project, expect: :update

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index

    @tasks = @project.tasks
  end





  # GET projects/1/tasks/1
  def show




    


    end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build

  end

  # GET projects/1/tasks/1/edit
  def edit

  end




  # POST projects/1/tasks
  def create

    @task = @project.tasks.build(task_params)
    @task.uid = current_user.id



    if @task.save
      redirect_to([@task.project,@task], notice: "#{I18n.t 'tasks.task_created'}")
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to([@task.project, @task], notice: "#{I18n.t 'tasks.task_updated'}")
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to projects_path(@project), notice: "#{I18n.t 'tasks.task_destroy'}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project

      @project = Project.find(params[:project_id])

    end

   def set_task
     @task = @project.tasks.find(params[:id])
  end

    # Only allow a trusted parameter "white list" through.
    def task_params

      params.require(:task).permit(:title, :description, :is_done, :project_id, :uid, :tag, :attachment)
    end




end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> <%="#{I18n.t 'forms.cannot_save'}" %></h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "#{I18n.t 'tasks.title'}" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "#{I18n.t 'forms.desc'}" %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.label "#{I18n.t 'tasks.file'}" %><br />
  <%= f.file_field :attachment %>
<br>

  <div class="field">

    <%= f.text_field :project, type: :hidden %>



<br>
    <%= f.check_box :is_done %>
    <%= f.label "#{I18n.t 'tasks.is_done?'}" %>
  </div>
  <div class="actions">
<br>
    <%= f.submit "#{I18n.t 'forms.submit'}", class:"btn btn-success" %>
  </div>
<% end %>

app/views/tasks/add_tags.html.erb
<%=@task %>

app/views/tasks/alltasks.html.erb
<h1>Všechny mé úkoly</h1>


<br><br>

<br>





<br />
<div class="card" style="width: 25rem;">
  <div class="card-header">
    Úkoly
  </div>
  <% @tasks.each do |task| %>
    <ul class="list-group list-group-flush">

      <% if task.is_done == true %>
      <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-success"%>
        <%else%>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-danger"%>
        <%end %>

  <%end %>





  </ul>
</div>
<br>
<%= link_to "Ukaž pouze hotové", home_only_comp_path, class:"btn btn-success" %>
<%= link_to "Ukaž pouze nedodělané", home_only_uncomp_path, class:"btn btn-secondary" %>

app/views/tasks/edit.html.erb
<h1><%= "#{I18n.t 'forms.edit'}" %> <%= "#{@task.title}" %></h1>

<%= render 'form' %>

<br>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Is done</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.is_done %></td>

    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1><%= "#{I18n.t 'tasks.new_task'}" %></h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p>
  <b><%= "#{I18n.t 'tasks.title'}" %> :</b>
  <%= @task.title %>
  <br>


</p>
<b><%="#{I18n.t 'forms.desc'}" %></b>
<%if @task.description.nil? == true %>
  <%= "#{I18n.t 'tasks.no_desc'}"%>
  <%else %>
<%= @task.description %>
<%end %>
<br>


  <br>
  <% if @task.is_done == true %>
  <strong><%="#{I18n.t 'tasks.comp_tasks'}" %></strong>
    <%else %>
   <%="#{I18n.t 'tasks.uncomp'}" %>
    <%end %>
  <br>
  <br>

  <%="#{I18n.t 'tasks.file'}" %>:
  <% if @task.attachment.nil? %>
  <strong><%="#{I18n.t 'tasks.without_file'}" %></strong>
    <%else %>
  <%=link_to "#{I18n.t 'tasks.download'}", @task.attachment_url %>
    <%end %>
  <br>

<br>








<%= link_to "#{I18n.t 'forms.edit'}", edit_project_task_path(@task.project, @task), class:"btn btn-dark" %>



<%= link_to "#{I18n.t 'forms.destroy'}", project_task_path, method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" }, class:"btn btn-danger" %>



<br><br>
<div class="card" style="width: 25rem;">
  <div class="card-header">
    <%= "#{I18n.t 'tags.tags'}" %>
  </div>
  <% @task.tags.each do |tag| %>
    <ul class="list-group list-group-flush">


      <%= link_to "#{tag.title}", [tag.task, tag], class:"list-group-item card bg-secondary"%>

  <%end %>

  <%= link_to "#{I18n.t 'tags.new_tag'}", new_task_tag_path(@task), class:"btn btn-success" %>