config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    resources :tags
  end
  namespace :task do
    resources :tags
  end
  root 'projects#index'
  get 'tasks/delete'
  get 'tags/delete'
  get 'projects/last_projects'
  get 'projects/first_projects'

  resources :projects do
    resources :tasks
  end
  resources :tasks do
    end

  get 'home/alltasks' #Tasks
  get 'home/only_comp' #tasks
  get 'home/only_uncomp' #tasks
  get 'home/search' #search
  get 'home/alltags'# Tags
  get 'home/index2'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index



  end

  def index2
    @pagy, @projects = pagy(Project.where(:uid => current_user.id))
  end


  def search
    if current_user.nil?
      redirect_to new_user_session_path, notice: "#{I18n.t 'login.need_to_login'}"
    else
      @projects = Project.search(params[:search]).where(uid: current_user.id)
      @tasks = Task.search(params[:search]).where(uid: current_user.id)
      @tags = Tag.search(params[:search]).where(uid: current_user.id)

    end
    end


  def only_comp


    @tasks = Task.comp_tasks.where(uid: current_user.id)

  end

  def only_uncomp
      @tasks = Task.uncomp_tasks.where(uid: current_user.id)


  end

  def alltasks



    if current_user.nil?
      redirect_to new_user_session_path, notice: "#{I18n.t 'login.need_to_login'}"
      else
      @pagy, @tasks = pagy (Task.where(:uid => current_user.id).includes([:project]))
      end

  end


  def alltags

    @tags_titles = Array.new
    if current_user.nil?
      redirect_to new_user_session_path, notice: "#{I18n.t 'login.need_to_login'}"
    else
    @pagy, @tags = pagy( Tag.where(:uid => current_user.id).includes([:task]) )
    end




    end





end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Projekty™", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

          <%= link_to "#{I18n.t 'project.projects'}", projects_path, class:"nav-link active" %>




        </li>
        <li>

          <%= link_to "#{I18n.t 'tasks.tasks'}", home_alltasks_path, class:"nav-link active" %>


        </li>

        <li>

            <%= link_to "#{I18n.t 'tags.tags'}" , home_alltags_path, class:"nav-link active" %>

        </li>



      </ul>
      <%= form_with url: home_search_path, method: :get do |form| %>
      <%= form.text_field :search, placeholder:"#{I18n.t 'searchs.search'}" %>

      <% end %>




      <%if current_user.nil? == false %>
          <%= link_to "#{current_user.email}", edit_user_registration_path, class: "btn btn-dark"%>
        <%end%>
        <%if current_user.nil? %>
        <%= link_to "#{I18n.t 'login.login'}", new_user_session_path, class:"btn btn-success" %>
          <%else %>
        <%= link_to "#{I18n.t 'login.logout'}", destroy_user_session_path, :method => :delete, class:"btn btn-danger"%>
          <%end %>


      </form>
    </div>
  </div>
</nav>

app/views/home/alltags.html.erb
<h1><%="#{I18n.t 'tags.all_my_tags'}" %></h1>


<br><br>

<br>


<table class="table table-striped">
  <thead>
  <tr>
    <th><%="#{I18n.t 'project.title'}" %></th>
    <th><%="#{I18n.t 'tags.under_task'}" %></th>
    <th colspan="5"></th>
  </tr>
  </thead>


  <tbody>
  <% @tags.each do |tag| %>

    <tr>
      <td><%= tag.title %></td>
      <td><%= tag.task.title %></td>
      <td><%= link_to "#{I18n.t 'forms.show'}",[tag.task, tag] , class: "btn btn-secondary" %></td>
      <td><%= link_to "#{I18n.t 'forms.edit'}", edit_task_tag_path(tag.task, tag), class: "btn btn-dark" %></td>
      <td><%= link_to "#{I18n.t 'forms.destroy'}",[tag.task, tag], method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" }, class:"btn btn-danger" %></td>
    </tr>

  <% end %>
  </tbody>
</table>






<br>

<br>
<br>
<br>
<%==pagy_nav(@pagy) %>

app/views/home/alltasks.html.erb
<h1><%= "#{I18n.t 'tasks.all_my_tasks'}" %></h1>


<br><br>

<br>





<br />
<div class="card" style="width: 25rem;">
  <div class="card-header">
    <%= "#{I18n.t 'tasks.tasks'}" %>
  </div>
  <% @tasks.each do |task| %>
    <ul class="list-group list-group-flush">

      <% if task.is_done == true %>
      <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-success"%>
        <%else%>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-danger"%>
        <%end %>

  <%end %>





  </ul>
</div>
<br>
<%= link_to "#{I18n.t 'tasks.comp_tasks'}", home_only_comp_path, class:"btn btn-success" %>
<%= link_to "#{I18n.t 'tasks.un_comp_tasks'}", home_only_uncomp_path, class:"btn btn-secondary" %>
<br>
<br>
<br>
<%==pagy_nav(@pagy) %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index2.html.slim
html
head

h1 ="#{I18n.t 'project.projects'}"

table class="table table-striped"

  thead

    tr
      strong ="#{I18n.t 'project.title'}"


    tr
  thead


  tbody
    - @projects.each do |project|
      - if project.uid == current_user.id
      tr
        td =project.title

        td =link_to "#{I18n.t 'forms.show'}", project, class: "btn btn-secondary"
        td =link_to "#{I18n.t 'forms.edit'}", edit_project_path(project), class: "btn btn-dark"
        td =link_to "#{I18n.t 'forms.destroy'}", project, method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" }, class:"btn btn-danger"
      tr
      end
      end
  tbody
table

br

=link_to "#{I18n.t 'project.new_project'}", new_project_path, class:"btn btn-success"
=link_to "#{I18n.t 'project.sort_first'}", projects_last_projects_path, class:"btn btn-dark"
head
htm

==pagy_nav(@pagy)

app/views/home/only_comp.html.erb
<h1><%="#{I18n.t 'tasks.comp_tasks'}" %></h1>




<br />
<div class="card" style="width: 25rem;">
  <div class="card-header">
    <%="#{I18n.t 'tasks.tasks'}" %>
  </div>
  <% @tasks.each do |task| %>
    <ul class="list-group list-group-flush">

      <% if task.is_done == true %>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-success"%>
      <%else%>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-danger"%>
      <%end %>

  <%end %>



  </ul>
</div>
<br>

<%= link_to "#{I18n.t 'tasks.all_my_tasks'}", home_alltasks_path , class:"btn btn-dark" %>
<%= link_to "#{I18n.t 'tasks.un_comp_tasks'}", home_only_uncomp_path , class:"btn btn-secondary" %>

app/views/home/only_uncomp.html.erb
<h1>Nedodělané úkoly</h1>




<br />
<div class="card" style="width: 25rem;">
  <div class="card-header">
    Úkoly
  </div>
  <% @tasks.each do |task| %>
    <ul class="list-group list-group-flush">

      <% if task.is_done == true %>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-success"%>
      <%else%>
        <%= link_to "#{task.title}", [task.project, task], class:"list-group-item card bg-danger"%>
      <%end %>

  <%end %>



  </ul>
</div>
<br>
<%= link_to "#{I18n.t 'tasks.all_my_tasks'}", home_alltasks_path , class:"btn btn-secondary" %>
<%= link_to "#{I18n.t 'tasks.comp_tasks'}", home_only_comp_path , class:"btn btn-dark" %>

app/views/home/search.html.erb
<% if @projects.nil? == false %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%="#{I18n.t 'project.projects'}" %></th>

    <th colspan="3"></th>
  </tr>
  </thead>




<% @projects.each do |project| %>

    <tr>
      <td><%= highlight(project.title, params[:search]) %></td>

      <td><%= link_to "#{I18n.t 'forms.show'}", project, class: "btn btn-secondary" %></td>
      <td><%= link_to "#{I18n.t 'forms.edit'}", edit_project_path(project), class: "btn btn-dark" %></td>
      <td><%= link_to "#{I18n.t 'forms.destroy'}", project, method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" }, class:"btn btn-danger" %></td>
    </tr>
  <% end %>
<%end %> </table>

<% if @tasks.nil? == false %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%="#{I18n.t 'tasks.tasks'}" %></th>

      <th colspan="3"></th>
    </tr>
    </thead>




    <% @tasks.each do |task| %>

      <tr>
        <td><%= highlight(task.title, params[:search]) %></td>
        <td><%= link_to "#{I18n.t 'forms.show'}", [task.project, task], class:"btn btn-secondary" %></td>
        <td><%= link_to "#{I18n.t 'forms.edit'}", edit_project_task_path(task.project, task), class:"btn btn-dark" %></td>
        <td><%= link_to "#{I18n.t 'forms.destroy'}", [task.project, task], method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
<%end %>
</table>

<% if @tags.nil? == false %>

    <table class="table table-striped">
      <thead>
      <tr>
        <th><%="#{I18n.t 'tags.tags'}" %></th>
        <th><%= "#{I18n.t 'tags.under_task'}" %></th>
        <th colspan="4"></th>
      </tr>
      </thead>

      <% @tags.each do |tag| %>
        <tr>
          <td><%= highlight(tag.title, params[:search]) %></td>
          <td><%= "#{tag.task.title}"%></td>
          <td><%= link_to "#{I18n.t 'forms.show'}", [tag.task, tag], class: "btn btn-secondary" %></td>
          <td><%= link_to "#{I18n.t 'forms.edit'}", edit_task_tag_path(tag.task, tag), class:"btn btn-dark" %></td>
          <td><%= link_to "#{I18n.t 'forms.destroy'}", [tag.task, tag], method: :delete, data: { confirm: "#{I18n.t 'notice.are_you_sure'}" }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
      <%end %>
</table>